// Code generated by protoc-gen-go. DO NOT EDIT.
// source: registry.proto

package registry // import "."

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GrpcNodeInfo struct {
	Addr                 string   `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Transport            string   `protobuf:"bytes,2,opt,name=transport,proto3" json:"transport,omitempty"`
	Version              string   `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GrpcNodeInfo) Reset()         { *m = GrpcNodeInfo{} }
func (m *GrpcNodeInfo) String() string { return proto.CompactTextString(m) }
func (*GrpcNodeInfo) ProtoMessage()    {}
func (*GrpcNodeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_registry_ed6ae9d2718cdabb, []int{0}
}
func (m *GrpcNodeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrpcNodeInfo.Unmarshal(m, b)
}
func (m *GrpcNodeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrpcNodeInfo.Marshal(b, m, deterministic)
}
func (dst *GrpcNodeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrpcNodeInfo.Merge(dst, src)
}
func (m *GrpcNodeInfo) XXX_Size() int {
	return xxx_messageInfo_GrpcNodeInfo.Size(m)
}
func (m *GrpcNodeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GrpcNodeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GrpcNodeInfo proto.InternalMessageInfo

func (m *GrpcNodeInfo) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *GrpcNodeInfo) GetTransport() string {
	if m != nil {
		return m.Transport
	}
	return ""
}

func (m *GrpcNodeInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func init() {
	proto.RegisterType((*GrpcNodeInfo)(nil), "GrpcNodeInfo")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RegistryClient is the client API for Registry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RegistryClient interface {
}

type registryClient struct {
	cc *grpc.ClientConn
}

func NewRegistryClient(cc *grpc.ClientConn) RegistryClient {
	return &registryClient{cc}
}

// RegistryServer is the server API for Registry service.
type RegistryServer interface {
}

func RegisterRegistryServer(s *grpc.Server, srv RegistryServer) {
	s.RegisterService(&_Registry_serviceDesc, srv)
}

var _Registry_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Registry",
	HandlerType: (*RegistryServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "registry.proto",
}

func init() { proto.RegisterFile("registry.proto", fileDescriptor_registry_ed6ae9d2718cdabb) }

var fileDescriptor_registry_ed6ae9d2718cdabb = []byte{
	// 129 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x4a, 0x4d, 0xcf,
	0x2c, 0x2e, 0x29, 0xaa, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x8a, 0xe2, 0xe2, 0x71, 0x2f,
	0x2a, 0x48, 0xf6, 0xcb, 0x4f, 0x49, 0xf5, 0xcc, 0x4b, 0xcb, 0x17, 0x12, 0xe2, 0x62, 0x49, 0x4c,
	0x49, 0x29, 0x92, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x85, 0x64, 0xb8, 0x38, 0x4b,
	0x8a, 0x12, 0xf3, 0x8a, 0x0b, 0xf2, 0x8b, 0x4a, 0x24, 0x98, 0xc0, 0x12, 0x08, 0x01, 0x21, 0x09,
	0x2e, 0xf6, 0xb2, 0xd4, 0xa2, 0xe2, 0xcc, 0xfc, 0x3c, 0x09, 0x66, 0xb0, 0x1c, 0x8c, 0x6b, 0xc4,
	0xc5, 0xc5, 0x11, 0x04, 0xb5, 0xcd, 0x89, 0x27, 0x8a, 0x4b, 0xcf, 0x1a, 0x66, 0x77, 0x12, 0x1b,
	0xd8, 0x72, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf9, 0x46, 0xad, 0x5d, 0x8e, 0x00, 0x00,
	0x00,
}
